# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven
permissions:
  contents: write  # Add this line to grant write permissions to contents
  
on:
  push:
    tags:
      - 'v*.*.*'  # Triggers the workflow on tags matching the pattern v1.2.3


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Install Ilog
      run: mvn install:install-file -Dfile="cplex-20.1.0.jar" -DgroupId="ilog" -DartifactId="cplex" -Dversion="20.1.0" -Dpackaging=jar -DgeneratePom=true
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Extract Tag Name
      id: extract_tag
      run: echo "TAG_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
    - name: Print Tag Name
      id: Print_tag
      run: echo ${{ env.TAG_NAME }}
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: Release ${{ env.TAG_NAME }}
        body: |
          Changes in this release:
          - Auto-generated release notes by GitHub Actions.
        draft: false
        prerelease: false

    - name: Upload JAR file to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: App/target/app-1.0-SNAPSHOT-jar-with-dependencies.jar  # Replace with your actual jar file name
        asset_name: app-1.0-SNAPSHOT-jar-with-dependencies.jar  # Replace with your actual jar file name
        asset_content_type: application/java-archive

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
      # uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
